config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# custom routes
  get "spaces", to: "spaces#index"
  patch "space/:id", to:'spaces#update'
  patch "user/:id", to:'users#update'
  get "user/:id", to: "users#show", as: :user
  get "dashboard", to: "users#dashboard", as: :dashboard
  get "spaces/new", to: "spaces#new"
  delete "picture/:id", to: 'pictures#destroy',as: :picture
  delete "booking/:id", to: 'bookings#destroy',as: :booking
  post "spaces", to: "spaces#create"
  get "space/:id/edit", to: 'spaces#edit', as: :space_edit
  get "user/:id/edit", to: 'users#edit', as: :user_edit
  delete "space/:id", to: 'spaces#destroy', as: :delete_space
  get "picture/:id", to: "pictures#edit", as: :edit_picture
  # patch "picture/:id", to: "pictures#update", as: :picture
  get "space/:id", to: "spaces#show", as: :space
  post "bookings", to: "bookings#create"
  # resources :users do
  #   resources :spaces
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # assosiations
  belongs_to :user
  belongs_to :space

  # validations
  validates :start_date, presence: true
  # validates :end_date, presence: true
  validates :rent, presence: true

end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :space
  mount_uploader :photo, PhotoUploader
end

app/models/space.rb
class Space < ApplicationRecord
  # assosiations
  belongs_to :user
  has_many :bookings
  has_many :pictures, dependent: :destroy

  #validations
  validates :name, presence: true
  validates :address, presence: true
  validates :capacity, presence: true
  validates :price, presence: true

  # allows use to create a space including with pictures as a parent to child see link for more info
  # https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html
  accepts_nested_attributes_for :pictures


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # assosiations
  has_many :spaces
  has_many :bookings
  mount_uploader :avatar, PhotoUploader
  # validations
  # validates :name, presence: true
  # validates :phone_number, presence: true
  # validates :avatar, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?


  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.space.capacity -= @booking.rent
    authorize @booking
    @booking.space.save
    @booking.user = current_user
    @booking.save ? (redirect_to dashboard_path):(render space_path(params[:id]))
  end


  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.space.capacity += @booking.rent
    @booking.space.save
    @booking.delete
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :rent, :space_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @spaces = Space.all
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController


  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
   if @picture.update(picture_params)
    redirect_to dashboard_path
    else
    render :edit
    end
  end


  def destroy
    @picture = Picture.find(params[:id])
    authorize @picture
    @picture.destroy
    redirect_to  space_edit_path(@picture.space)
  end

  private

  def picture_params
    params.require(:picture).permit(:id, :space_id, :photo)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @spaces = policy_scope(Space.where.not(latitude: nil, longitude: nil))

    @markers = @spaces.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def show
    @space = Space.find(params[:id])
    authorize @space

    @booking = Booking.new
    @booking.end_date = 30.days.from_now # Just here for presentation
    @booking.rent = 5 # just here for presentation
  end

  def new
    @space = Space.new()

    # everything below here is for presetation
    @space.name = "My Basement"
    @space.capacity = 12
    @space.price = 25
    @space.description = "A very clean basement in the center of Amsterdam"
    @pictures= @space.pictures.build

    authorize @space
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    authorize @space
    if @space.save
      params[:pictures]['photo'].each do |a|
        @picture= @space.pictures.create!(:photo => a)
      end
      (redirect_to space_path(@space))
    else
      (render :new)
    end
  end

  def edit
    @space = Space.find(params[:id])
    authorize @space
    @pictures = @space.pictures
  end

  def update
    @space = Space.find(params[:id])
    authorize @space
    # raise
    if @space.update(space_params)
      params[:pictures]['photo'].each do |a|
        @picture= @space.pictures.create!(:photo => a)
      end
      (redirect_to space_path(@space))

    else
      (render :edit)
    end
  end

  def destroy

    @space = Space.find(params[:id])
    authorize @space
    @space.destroy
  end

  private

  def space_params
    params.require(:space).permit(:name, :address, :price, :capacity, :description , pictures_attributes: [:id,:space_id,:photo])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :authenticate_user!, only: [:show]
  def show
    @user = User.find(params[:id])
    authorize @user

    @spaces = Space.where(user_id: @user)
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def dashboard
    if user_signed_in?
      @user = User.find(current_user.id)
      authorize @user
      @spaces = Space.where(user_id: current_user)
    else
      redirect_to new_user_session_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :about, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Space  Maker</title>
  <link rel="stylesheet" href="https://use.typekit.net/euj0cvj.css">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>
  <%= render "shared/navbar" %>
  <div class="content-wrapper">
    <% unless notice.nil? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
     <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_pack_tag "map" %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner-main" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path("space_banner.jpg") %>);">
  <div class="banner-content">
    <h1 id="banner-heading1">Space  Maker</h1>
    <h2 id="banner-heading2">"Get your space on"</h2>
    <% if user_signed_in? %>
      <%= link_to "Spaces", dashboard_path, class: "button button-primary"  %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "button button-primary"  %>
    <% end %>
  </div>
</div>

<div class="card_container">
  <h3 class="text-center">Nearby spaces</h3>
<%= render "shared/card" %>
</div>

<div class="multi-column-container">
  <div class="two-column-content">
    <div>
      <h3>Why use space maker?</h3>
      <p>Let’s face it, most of us can afford less and less space in the big cities we call home. But what are we supposed to do with all of our stuff? Space maker helps you find unutilized space near you! Save money and save space. </p>
      <% if user_signed_in? %>
        <div class="homepage-button-flex">
          <%= link_to "Spaces", dashboard_path, class: "button button-primary"  %>
        </div>
      <% else %>
        <div class="homepage-button-flex">
          <%= link_to "Register", new_user_registration_path, class: "button button-primary"  %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="two-column-content">
    <%= image_tag "homepage-boxes.svg", class: "homepage-image" %>
  </div>
</div>

<div class="multi-column-container">
  <div class="two-column-content">
    <%= image_tag "homepage-neighbors.svg", class: "homepage-image" %>
  </div>
  <div class="two-column-content">
    <div>
      <h3>Still not convinced?</h3>
      <h4>Here is why we're awesome</h4>
      <p>Space maker saves people an average of 60% on storage costs relative to traditional storage units. While most storage units are located far away, your neighbor’s basement is just down the street. Oh, and wouldn’t you rather help out your neighbor than some random company? </p>
      <h4>Here is why our competitor is not.</h4>
      <p>Traditional storage units are usually located outside of the city limits making the task of getting something of yours rather challenging. Did we mention how much more expensive they are?</p>
      <% if user_signed_in? %>
        <div class="homepage-button-flex">
          <%= link_to "Spaces", dashboard_path, class: "button button-primary"  %>
        </div>
      <% else %>
        <div class="homepage-button-flex">
          <%= link_to "Register", new_user_registration_path, class: "button button-primary"  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="multi-column-container">
  <div class="two-column-content">
    <div>
      <h3>Want to make some money on the side?</h3>
      <p>If you happen to be one of the lucky ones with extra unutilized space on your hands, start generating income by storing your neighbor’s things! Who knew doing so little could pay so well.
      </p>
      <% if user_signed_in? %>
        <div class="homepage-button-flex">
          <%= link_to "Spaces", dashboard_path, class: "button button-primary"  %>
        </div>
      <% else %>
        <div class="homepage-button-flex">
          <%= link_to "Register", new_user_registration_path, class: "button button-primary"  %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="two-column-content">
    <%= image_tag "homepage-garage.svg", class: "homepage-image" %>
  </div>
</div>

<% if !user_signed_in? %>
  <div class="main-container">
    <div class="one-column-content">
      <div class="centered-text">
        <h3>Just sign up!</h3>
          <%= link_to "Register", new_user_registration_path, class: "button button-primary"  %>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/profile.html.erb
<div class="container">
  <div>
    <div class="row">
      <h1><%= @user.name %></h1>
    </div>
    <div class="avatar">
      <%= image_tag "source", alt: "avatar" %>
    </div>
  </div>
  <% @user.spaces.each do |space| %>
  <div class="row">
    <p><%= space.name %></p>
    <p> <%= space.address %> </p>
  </div>
  <%= end %>
</div>

app/views/pictures/edit.html.erb
<h1>This works</h1>


<%= cl_image_tag @picture.photo, height: 300, width: 400, crop: :fill %>
<%= form_for(@picture) do |f| %>
  <div class="field">
     <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_card.html.erb
 <div class="row_card">
    <% Space.order("RANDOM()").first(3).each do |space| %>
      <%
        picture = space.pictures.first
        if picture
          image_path = cl_image_path(picture.photo)
        else
          image_path = " "
        end
      %>

      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( <%= image_path %>);">
          <h3><%= space.name %></h3>
          <p><%= space.address %></p>
          <div class="capacity-counter">
            <p><strong><%= space.capacity %></strong> spaces left</p>
          </div>
          <%= link_to "",space_path(space), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
<!--     <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a> -->
  </div>
  <div class="footer-copyright">
  <p>Copyright @ 2018 Space Maker Inc. All rights reserved.</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "space_maker.svg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Spaces", spaces_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% if !current_user %>
      <%= link_to "Log in", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user %>
        <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag " " %>
          <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to dashboard_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
            <% end %>
            <% if current_user %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <%= link_to dashboard_path do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Dashboard") %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_photo.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
<% array_of_photos.each_with_index do |picture, index| %>
    <% if index == 0 %>
      <div class="item active">
        <%= picture %>
        <div class="carousel-caption">
        </div>
      </div>
    <% else  %>
      <div class="item">
        <%= picture %>
        <div class="carousel-caption">
        </div>
      </div>
    <% end %>
<% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/spaces/destroy.js.erb
document.querySelector("[data-space-id='<%= @space.id %>']")
  .remove();

app/views/spaces/edit.html.erb
  <div class="main-container primary-bg">
    <div class="form-holder form-text-white">
      <h1 class="form-h1-title">Edit <%= @space.name %></h1>
      <%= simple_form_for(@space) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :price %>
        <%= f.input :capacity %>
        <%= f.input :description %>
        <div class="form-group">
          <%= f.fields_for :pictures_attributes do |p| %>
            <%= p.label :photo %><br>
            <%= p.file_field :photo, :multiple => true, name: "pictures[photo][]"%>
          <% end %>
        </div>
          <%= f.button :submit, class: "button button-green", style: "margin-top: 20px", id: "form-button" %>
      <% end %>
    </div>

  <div class="box-around-pictures">
    <div class= "inline-pictures">
      <% @pictures.each do |p| %>
        <div class = "border-picture col-xs-3">
          <%= cl_image_tag p.photo, height: 100, width: 133, crop: :fill %>
          <% if @pictures.count > 1 %>
          <div class = "delete-picture-link">
            <%= link_to "", picture_path(p), method: :delete, class: "fas fa-times" %>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spaces/index.html.erb
<div class="map-side">
  <div
  id="map"
  data-markers="<%= @markers.to_json %>"
  ></div>
</div>
<div class="main-container">
  <div class="list-cards list-container">
    <% @spaces.each do |space| %>
    <div class="list-card">
      <% if !space.pictures.first.present? %>
        <%= image_tag "dumb_avatar.png", class: "card-image"%>
      <% else %>
        <%= (cl_image_tag(space.pictures.first.photo, class: "card-image" ))%>
      <% end %>
      <div class="list-card-info">
        <%= link_to space_path(space) do %>
          <h3 class="card-header"><%= space.name %></h3>
        <% end %>
        <p><strong>Owner: </strong><%= space.user.name %></p>
        <p><strong>Address: </strong><%= space.address %></p>
        <p><strong>Capacity: </strong><%= space.capacity %>m³</p>
        <p><strong>Price: </strong>€<%= space.price %> (per month)</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/spaces/new.html.erb
<div class="main-container primary-bg">
  <div class="form-holder form-text-white">
    <h1 class="form-h1-title">Add space</h1>
    <%= simple_form_for(@space) do |f| %>
      <%= f.input :name %>
      <%= f.input :address, input_html: { id: 'space_address' }%>
      <%= f.input :price %>
      <%= f.input :capacity %>
      <%= f.input :description %>
      <%= f.fields_for :pictures_attributes do |p| %>
        <%= p.label :photo %><br>
        <%= p.file_field :photo, :multiple => true, name: "pictures[photo][]"%>
      <% end %>

      <%= f.button :submit, class: "button button-green", style: "margin-top: 20px", id: "form-button" %>
    <% end %>
  </div>
</div>

app/views/spaces/show.html.erb
<!-- the following code should alsways be on top -->
<% array_of_photos = [] %>
<% @space.pictures.each do |picture| %>
  <% array_of_photos << (cl_image_tag picture.photo, height: 300, width: 400, crop: :fill)%>
<% end %>

<div class="show-container add-bottom-margin">
  <div class="row">
    <% if !current_user %>
      <div class="link-wrapper-out">
        <%= link_to "Go back", spaces_path, class: "button button-primary"  %>
      </div>
      <% else %>
      <div class="link-wrapper-in">
        <%= link_to "Go back", spaces_path, class: "button button-primary"  %>
        <%= link_to "Edit space", space_edit_path, class: "button button-green" %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="space-information">
      <h3><%= @space.name.capitalize %></h3>

      <div class = "photo-container">
        <%= render "shared/photo", array_of_photos: array_of_photos %>
      </div>

      <h3>Space information:</h3>
      <p><strong>Name: </strong><%= @space.name %></p>
      <p><strong>Address: </strong><%= @space.address %></p>
      <p><strong>Capacity: </strong><%= @space.capacity %> m²</p>
      <p><strong>Price: </strong>€ <%= @space.price %> (per month)</p>
      <p><strong>Owner: </strong> <%= link_to @space.user.name, user_path(@space.user) %></p>
    </div>

    <div class="space-information">
      <%= simple_form_for @booking do |b| %>
        <%= b.hidden_field :space_id, :value => @space.id %>
        <%= b.input :start_date %>
        <%= b.input :end_date %>
        <%= b.input :rent, collection: 0..@space.capacity %>
        <%= b.button :submit, class: "button button-green", id: "form-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="dashboard-container">

  <div class="dashboard-grid-image">
    <% if @user.avatar.present? %>
    <%= (cl_image_tag @user.avatar, width: 200, height: 200, crop: :thumb) %>
    <% else %>
    <%= image_tag "dumb_avatar.png", class: "avatar"%>
    <% end %>

  </div>

  <div class="dashboard-grid-info">
    <h1 class="dashboard-info-title"><%= link_to @user.name, user_path(@user) %></h1>
    <%= link_to "", user_edit_path(@user), class: "fas fa-user-edit dashboard-info-edit edit-icon" %>
    <p class="dashboard-info-text">phone number: <%= @user.phone_number %></p>
    <p class="dashboard-info-text">email: <%= @user.email %></p>
  </div>

  <div class="dashboard-grid-spaces">
    <div class="dashboard-list-header">
      <h3>Spaces</h3>
      <%= link_to "", spaces_new_path, class: "fas fa-plus dashboard-list-text dashboard-add" %>
    </div>
    <div class="dashboard-list">
      <% @user.spaces.each do |space| %>
        <div class="dashboard-list-item" data-space-id="<%= space.id %>">
          <%= link_to space.name, space_path(space), class: "dashboard-list-text dashboard-link" %>
          <div>
            <%= link_to "", space_edit_path(space), class: "fas fa-pencil-alt dashboard-edit" %>
            <%= link_to "", delete_space_path(space), method: :delete, remote: true, class: "fas fa-times dashboard-delete"%>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="dashboard-grid-bookings">
    <div class="dashboard-list-header">
      <h3>Bookings</h3>
    </div>
    <div class="dashboard-list">
      <% @user.bookings.each do |booking| %>
        <div class="dashboard-list-item">
          <%= link_to booking.space.name, space_path(booking.space), class: "dashboard-list-text dashboard-link"%>
          <p class="dashboard-list-text"><%= booking.rent %> m²</p>
          <p class="dashboard-list-text">€<%= booking.space.price %>,-</p>
          <%= link_to "", booking_path(booking), method: :delete, class: "fas fa-times dashboard-delete" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/destroy.js.erb
console.log("we got here ")


document.querySelector("[data-space-id='<%= @space.id %>']")
  .remove();

app/views/users/edit.html.erb
<div class="main-container primary-bg">
  <div class="form-holder form-text-white">
    <h1 class="form-h1-title">Edit profile</h1>
    <%= simple_form_for(@user) do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :phone_number %>
      <%= f.input :about %>
      <div class="form-group">
        <%= f.label "Avatar upload" %>
        <%= f.file_field :avatar, :multiple => false %>
        <%= f.input :avatar_cache, as: :hidden %>
      </div>
      <%= f.button :submit, class: "button button-green", style: "margin-top: 20px", id: "form-button" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="top-row id="top_row">
    <div class="avatar-profile">
      <% if @user.avatar.present? %>
      <%= (cl_image_tag @user.avatar, width: 200, height: 200, crop: :thumb, radius: :max) %>
      <% else %>
      <%= image_tag "dumb_avatar.png", class: "avatar"%>
      <% end %>
      <div class="username">
        <div>
          <h2><%= @user.name.capitalize %></h2>
        </div>
        <div>
          <p>Rating: 4/5 </p>
        </div>
      </div>
    </div>
     <div class="row_about">
      <div>
        <h3>About</h3>
      </div>
      <div>
        <p><%= @user.about %></p>
      </div>
    </div>
    </div>
  <div class="card_container">
    <h3>My Spaces</h3>
    <div class="row_card">
      <% @user.spaces.each do |space| %>
      <%
      picture = space.pictures.first
      if picture
        image_path = cl_image_path(picture.photo)
      else
        image_path = " "
      end
      %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( <%= image_path %>);">
          <%= link_to space_path(space) do %>
          <h3><%= space.name %></h3>
          <p> <%= space.address %> </p>
          <%= link_to "",space_path(space), class: "card-link" %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>